FRONT-2738 Breadcrumbs
alifcapital/alif-ui-kit-react pull request #49
Opened 2023-11-06 11:01 UTC by ManuchehrTilloev

2023-11-07 05:32 UTC, mkhushang requested changes

2023-11-07 05:32 UTC, mkhushang commented on src/components/Breadcrumbs/BreadcrumbsTypes.ts
> +  href: string;
надо добавить еще key: number - required

2023-11-07 05:32 UTC, mkhushang commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +            <li className="Breadcrumbs-item" key={index}>
когда добавишь key в пропсах, key={item.key}

2023-11-07 05:32 UTC, mkhushang commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +          const isCurrent = items.length - 1 === index;
isCurrent тут лучше не объявлять

2023-11-07 05:36 UTC, Odinaev444 commented on src/components/Breadcrumbs/Breadcrumbs.tsx
accessibility хромает.

2023-11-07 08:37 UTC, ManuchehrTilloev commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +          const isCurrent = items.length - 1 === index;
решили оставить

2023-11-07 12:49 UTC, Odinaev444 submitted a review, later dismissed

2023-11-08 04:44 UTC, mkhushang approved these changes

2023-11-08 04:44 UTC, merged